// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@webcheckly.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/scan": {
            "get": {
                "description": "使用Server-Sent Events进行实时流式扫描。此接口已废弃，建议使用任务管理API（POST /api/scans）。\n\nSSE事件类型：\n- start: 扫描开始\n- result: 单个链接检测结果\n- progress: 进度更新\n- website-info: 网站信息\n- domain-info: 域名信息\n- ssl-info: SSL证书信息\n- tech-stack: 技术栈信息\n- performance-info: 性能指标\n- seo-info: SEO合规性\n- security-info: 安全风险\n- accessibility-info: 可访问性\n- ai-analysis: AI分析报告\n- done: 扫描完成\n- error: 错误信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "扫描"
                ],
                "summary": "SSE扫描接口（降级方案）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "扫描选项",
                        "name": "options",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "zh",
                            "en"
                        ],
                        "type": "string",
                        "default": "zh",
                        "description": "语言",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "performance",
                            "security",
                            "seo",
                            "balanced"
                        ],
                        "type": "string",
                        "default": "balanced",
                        "description": "AI分析模式",
                        "name": "ai_mode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE事件流（text/event-stream格式）",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误（URL格式错误、私有IP等）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "请求过于频繁（触发限流）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "服务繁忙（并发任务数已达上限）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/scans": {
            "post": {
                "description": "创建一个新的网站扫描任务，支持多种检测选项。任务创建后会异步执行，可通过任务ID查询状态和结果。\n\n支持的扫描选项：\n- website-info: 网站基础信息（标题、描述、关键词等）\n- domain-info: 域名DNS信息（IP、MX、NS、TXT记录等）\n- ssl-info: SSL证书信息（有效期、签名算法等）\n- tech-stack: 技术栈识别（框架、CMS、CDN等）\n- link-health: 链接健康检查（检测页面内所有链接的可用性）\n- performance: 性能检测（Lighthouse性能指标）\n- seo: SEO合规性检测（Lighthouse SEO指标）\n- security: 安全风险检测（Lighthouse安全指标）\n- accessibility: 可访问性检测（Lighthouse A11y指标）\n- ai-analysis: AI智能分析报告（需要配置DEEPSEEK_API_KEY）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "创建扫描任务",
                "parameters": [
                    {
                        "description": "任务创建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "任务创建成功，返回任务ID和初始状态",
                        "schema": {
                            "$ref": "#/definitions/models.CreateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误（URL格式错误、私有IP等）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/scans/{id}": {
            "get": {
                "description": "查询指定任务的执行状态和进度信息，包括各模块的执行状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "获取任务状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务状态",
                        "schema": {
                            "$ref": "#/definitions/models.TaskStatusResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/scans/{id}/results": {
            "get": {
                "description": "获取已完成任务的扫描结果数据。只有当任务状态为\"completed\"时才能获取完整结果。\n如果任务仍在执行中，将返回202状态码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "获取任务结果",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务结果（包含所有检测模块的结果数据）",
                        "schema": {
                            "$ref": "#/definitions/models.TaskResults"
                        }
                    },
                    "202": {
                        "description": "结果尚未准备好（任务仍在执行中）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务是否正常运行，返回服务状态和当前时间戳。此接口不受限流影响，可用于监控服务可用性。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务状态正常",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AIAnalysis": {
            "description": "AI生成的综合分析报告",
            "type": "object",
            "properties": {
                "availability_findings": {
                    "description": "分维度发现",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "所有链接均可正常访问"
                    ]
                },
                "availability_score": {
                    "description": "各维度评分（0-100），越高代表越好",
                    "type": "integer",
                    "example": 95
                },
                "highlights": {
                    "description": "关键发现列表（跨维度）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "网站加载速度较快",
                        "SSL证书配置正确"
                    ]
                },
                "performance_findings": {
                    "description": "性能方面的发现",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "LCP时间略高",
                        "建议优化图片加载"
                    ]
                },
                "performance_score": {
                    "description": "性能评分（响应时间等）",
                    "type": "integer",
                    "example": 80
                },
                "recommendations": {
                    "description": "综合建议与优化措施",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "建议添加CSP安全头",
                        "优化图片加载速度"
                    ]
                },
                "risk_level": {
                    "description": "整体风险等级：高 / 中 / 低",
                    "type": "string",
                    "enum": [
                        "高",
                        "中",
                        "低"
                    ],
                    "example": "中"
                },
                "security_findings": {
                    "description": "安全方面的发现",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "缺少CSP安全头"
                    ]
                },
                "security_score": {
                    "description": "安全评分（证书、安全头等）",
                    "type": "integer",
                    "example": 75
                },
                "seo_findings": {
                    "description": "SEO 方面的发现",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "元信息完整",
                        "robots.txt配置正确"
                    ]
                },
                "seo_score": {
                    "description": "SEO 评分（元信息、robots 等）",
                    "type": "integer",
                    "example": 90
                },
                "summary": {
                    "description": "总结性描述（自然语言）",
                    "type": "string",
                    "example": "网站整体表现良好，但存在一些性能和安全优化空间"
                }
            }
        },
        "models.AccessibilityInfo": {
            "description": "Lighthouse可访问性检测结果",
            "type": "object",
            "properties": {
                "findings": {
                    "description": "主要发现项",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Images missing alt text"
                    ]
                },
                "score": {
                    "description": "可访问性评分 (0-100)",
                    "type": "integer",
                    "example": 88
                }
            }
        },
        "models.CreateTaskRequest": {
            "description": "创建扫描任务的请求参数",
            "type": "object",
            "properties": {
                "ai_mode": {
                    "description": "AI分析模式",
                    "type": "string",
                    "default": "balanced",
                    "enum": [
                        "performance",
                        "security",
                        "seo",
                        "balanced"
                    ],
                    "example": "balanced"
                },
                "language": {
                    "description": "语言 (zh/en)",
                    "type": "string",
                    "default": "zh",
                    "enum": [
                        "zh",
                        "en"
                    ],
                    "example": "zh"
                },
                "options": {
                    "description": "扫描选项",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "website-info",
                        "domain-info"
                    ]
                },
                "url": {
                    "description": "目标URL",
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "models.CreateTaskResponse": {
            "description": "创建任务成功后的响应",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "enum": [
                        "pending",
                        "running",
                        "completed",
                        "failed"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskStatus"
                        }
                    ],
                    "example": "pending"
                }
            }
        },
        "models.DomainInfo": {
            "description": "域名DNS和地理位置信息",
            "type": "object",
            "properties": {
                "asn": {
                    "description": "ASN信息",
                    "type": "string",
                    "example": "AS15133"
                },
                "asn_name": {
                    "description": "ASN名称",
                    "type": "string",
                    "example": "Edgecast Inc."
                },
                "city": {
                    "description": "城市",
                    "type": "string",
                    "example": "New York"
                },
                "country": {
                    "description": "国家",
                    "type": "string",
                    "example": "US"
                },
                "domain": {
                    "type": "string",
                    "example": "example.com"
                },
                "ip": {
                    "type": "string",
                    "example": "93.184.216.34"
                },
                "ipv4": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "93.184.216.34"
                    ]
                },
                "ipv6": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2606:2800:220:1:248:1893:25c8:1946"
                    ]
                },
                "isp": {
                    "description": "ISP",
                    "type": "string",
                    "example": "Edgecast Inc."
                },
                "mx": {
                    "description": "MX记录",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "mail.example.com"
                    ]
                },
                "ns": {
                    "description": "NS记录",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ns1.example.com"
                    ]
                },
                "organization": {
                    "description": "组织",
                    "type": "string",
                    "example": "Example Inc."
                },
                "txt": {
                    "description": "TXT记录",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "v=spf1 include:_spf.example.com ~all"
                    ]
                }
            }
        },
        "models.HttpxResult": {
            "description": "httpx检测的单个URL结果",
            "type": "object",
            "properties": {
                "cdn": {
                    "type": "boolean",
                    "example": false
                },
                "ip": {
                    "type": "string",
                    "example": "93.184.216.34"
                },
                "response_time": {
                    "type": "integer",
                    "example": 150
                },
                "status": {
                    "type": "integer",
                    "example": 200
                },
                "title": {
                    "type": "string",
                    "example": "Example Domain"
                },
                "tls": {
                    "type": "boolean",
                    "example": true
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "models.ModuleStatus": {
            "description": "单个检测模块的执行状态",
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "完成时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "error": {
                    "description": "错误信息（如果有）",
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "description": "模块名称",
                    "type": "string",
                    "example": "website-info"
                },
                "progress": {
                    "description": "模块进度",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskProgress"
                        }
                    ]
                },
                "started_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "模块状态",
                    "enum": [
                        "pending",
                        "running",
                        "completed",
                        "failed"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskStatus"
                        }
                    ],
                    "example": "running"
                }
            }
        },
        "models.PerformanceMetrics": {
            "description": "Lighthouse性能检测指标",
            "type": "object",
            "properties": {
                "cls": {
                    "description": "Cumulative Layout Shift",
                    "type": "number",
                    "example": 0.1
                },
                "cls_score": {
                    "description": "CLS 评分",
                    "type": "integer",
                    "example": 95
                },
                "fcp": {
                    "description": "First Contentful Paint (ms)",
                    "type": "number",
                    "example": 1200.5
                },
                "fcp_score": {
                    "description": "FCP 评分",
                    "type": "integer",
                    "example": 90
                },
                "lcp": {
                    "description": "Largest Contentful Paint (ms)",
                    "type": "number",
                    "example": 2500
                },
                "lcp_element": {
                    "description": "LCP 元素定位",
                    "type": "string",
                    "example": "\u003cimg src=\"hero.jpg\"\u003e"
                },
                "lcp_score": {
                    "description": "LCP 评分",
                    "type": "integer",
                    "example": 85
                },
                "score": {
                    "description": "整体性能评分 (0-100)",
                    "type": "integer",
                    "example": 85
                },
                "speed_index": {
                    "description": "Speed Index (ms)",
                    "type": "number",
                    "example": 3000
                },
                "speed_index_score": {
                    "description": "Speed Index 评分",
                    "type": "integer",
                    "example": 85
                },
                "tbt": {
                    "description": "Total Blocking Time (ms)",
                    "type": "number",
                    "example": 200
                },
                "tbt_score": {
                    "description": "TBT 评分",
                    "type": "integer",
                    "example": 80
                }
            }
        },
        "models.SEOCompliance": {
            "description": "Lighthouse SEO检测结果",
            "type": "object",
            "properties": {
                "has_canonical": {
                    "description": "是否有 canonical 标签",
                    "type": "boolean",
                    "example": true
                },
                "has_description": {
                    "description": "是否有 Description",
                    "type": "boolean",
                    "example": true
                },
                "has_robots_txt": {
                    "description": "是否有 robots.txt",
                    "type": "boolean",
                    "example": true
                },
                "has_title": {
                    "description": "是否有 Title",
                    "type": "boolean",
                    "example": true
                },
                "has_viewport": {
                    "description": "是否有 Viewport",
                    "type": "boolean",
                    "example": true
                },
                "indexable": {
                    "description": "是否可索引",
                    "type": "boolean",
                    "example": true
                },
                "score": {
                    "description": "SEO 评分 (0-100)",
                    "type": "integer",
                    "example": 90
                },
                "spa_visibility": {
                    "description": "SPA 可见性 (Text Ratio: raw vs rendered)",
                    "type": "number",
                    "example": 0.85
                }
            }
        },
        "models.SSLInfo": {
            "description": "SSL/TLS证书详细信息",
            "type": "object",
            "properties": {
                "common_name": {
                    "description": "通用名称",
                    "type": "string",
                    "example": "example.com"
                },
                "country": {
                    "description": "国家",
                    "type": "string",
                    "example": "US"
                },
                "days_remaining": {
                    "description": "剩余天数",
                    "type": "integer",
                    "example": 90
                },
                "dns_names": {
                    "description": "SAN域名列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "example.com",
                        "www.example.com"
                    ]
                },
                "is_valid": {
                    "description": "是否有效",
                    "type": "boolean",
                    "example": true
                },
                "issuer": {
                    "description": "颁发者",
                    "type": "string",
                    "example": "CN=Let's Encrypt Authority X3"
                },
                "key_size": {
                    "description": "密钥长度",
                    "type": "integer",
                    "example": 2048
                },
                "locality": {
                    "description": "地区",
                    "type": "string",
                    "example": "San Francisco"
                },
                "organization": {
                    "description": "组织",
                    "type": "string",
                    "example": "Example Inc."
                },
                "organization_unit": {
                    "description": "组织单位",
                    "type": "string",
                    "example": "IT Department"
                },
                "province": {
                    "description": "省份",
                    "type": "string",
                    "example": "CA"
                },
                "public_key_alg": {
                    "description": "公钥算法",
                    "type": "string",
                    "example": "RSA"
                },
                "serial_number": {
                    "description": "序列号",
                    "type": "string",
                    "example": "1234567890ABCDEF"
                },
                "signature_alg": {
                    "description": "签名算法",
                    "type": "string",
                    "example": "SHA256-RSA"
                },
                "subject": {
                    "description": "主题",
                    "type": "string",
                    "example": "CN=example.com"
                },
                "valid_from": {
                    "description": "有效期开始",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "valid_to": {
                    "description": "有效期结束",
                    "type": "string",
                    "example": "2024-04-01T00:00:00Z"
                }
            }
        },
        "models.ScanSummary": {
            "description": "扫描任务的统计摘要信息",
            "type": "object",
            "properties": {
                "alive": {
                    "description": "可用 URL 数",
                    "type": "integer",
                    "example": 95
                },
                "avg_response": {
                    "description": "平均响应时间（毫秒）",
                    "type": "integer",
                    "example": 150
                },
                "dead": {
                    "description": "不可用 URL 数",
                    "type": "integer",
                    "example": 5
                },
                "timeout": {
                    "description": "是否发生超时",
                    "type": "boolean",
                    "example": false
                },
                "total": {
                    "description": "总 URL 数",
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "models.SecurityRisk": {
            "description": "Lighthouse安全检测结果",
            "type": "object",
            "properties": {
                "score": {
                    "description": "安全评分 (0-100)",
                    "type": "integer",
                    "example": 75
                },
                "script_count": {
                    "description": "脚本总数",
                    "type": "integer",
                    "example": 10
                },
                "security_headers": {
                    "description": "安全响应头 (CSP, HSTS等)",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "Strict-Transport-Security": "max-age=31536000"
                    }
                },
                "third_party_scripts": {
                    "description": "第三方脚本来源",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://cdn.example.com"
                    ]
                },
                "vulnerabilities": {
                    "description": "发现的潜在漏洞",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Missing CSP header"
                    ]
                }
            }
        },
        "models.TaskProgress": {
            "description": "任务执行进度信息",
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前进度",
                    "type": "integer",
                    "example": 5
                },
                "total": {
                    "description": "总进度",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.TaskResults": {
            "description": "扫描任务的完整结果数据",
            "type": "object",
            "properties": {
                "accessibility": {
                    "$ref": "#/definitions/models.AccessibilityInfo"
                },
                "ai_analysis": {
                    "description": "AI 分析",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AIAnalysis"
                        }
                    ]
                },
                "domain_info": {
                    "$ref": "#/definitions/models.DomainInfo"
                },
                "link_health": {
                    "description": "链接健康检查结果",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HttpxResult"
                    }
                },
                "performance": {
                    "description": "Lighthouse 相关结果",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PerformanceMetrics"
                        }
                    ]
                },
                "security_risk": {
                    "$ref": "#/definitions/models.SecurityRisk"
                },
                "seo_compliance": {
                    "$ref": "#/definitions/models.SEOCompliance"
                },
                "ssl_info": {
                    "$ref": "#/definitions/models.SSLInfo"
                },
                "summary": {
                    "description": "统计信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ScanSummary"
                        }
                    ]
                },
                "tech_stack": {
                    "$ref": "#/definitions/models.TechStack"
                },
                "website_info": {
                    "description": "基础信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.WebsiteInfo"
                        }
                    ]
                }
            }
        },
        "models.TaskStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "completed",
                "failed"
            ],
            "x-enum-comments": {
                "TaskStatusCompleted": "已完成",
                "TaskStatusFailed": "执行失败",
                "TaskStatusPending": "等待执行",
                "TaskStatusRunning": "执行中"
            },
            "x-enum-descriptions": [
                "等待执行",
                "执行中",
                "已完成",
                "执行失败"
            ],
            "x-enum-varnames": [
                "TaskStatusPending",
                "TaskStatusRunning",
                "TaskStatusCompleted",
                "TaskStatusFailed"
            ]
        },
        "models.TaskStatusResponse": {
            "description": "任务状态查询响应",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "modules": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.ModuleStatus"
                    }
                },
                "progress": {
                    "$ref": "#/definitions/models.TaskProgress"
                },
                "status": {
                    "enum": [
                        "pending",
                        "running",
                        "completed",
                        "failed"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskStatus"
                        }
                    ],
                    "example": "running"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "models.TechStack": {
            "description": "网站使用的技术栈和服务器信息",
            "type": "object",
            "properties": {
                "analytics": {
                    "description": "分析工具",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Google Analytics"
                    ]
                },
                "cache": {
                    "description": "缓存技术",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Redis"
                    ]
                },
                "cdn": {
                    "description": "CDN服务",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Cloudflare"
                    ]
                },
                "cms": {
                    "description": "CMS系统",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "WordPress"
                    ]
                },
                "content_length": {
                    "description": "Content-Length",
                    "type": "integer",
                    "example": 12345
                },
                "content_type": {
                    "description": "Content-Type",
                    "type": "string",
                    "example": "text/html; charset=UTF-8"
                },
                "database": {
                    "description": "数据库",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "MySQL"
                    ]
                },
                "etag": {
                    "description": "ETag",
                    "type": "string",
                    "example": "\"abc123\""
                },
                "framework": {
                    "description": "框架",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Laravel"
                    ]
                },
                "javascript_lib": {
                    "description": "JavaScript库",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "jQuery",
                        "React"
                    ]
                },
                "language": {
                    "description": "编程语言",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "PHP",
                        "JavaScript"
                    ]
                },
                "last_modified": {
                    "description": "Last-Modified",
                    "type": "string",
                    "example": "Mon, 01 Jan 2024 00:00:00 GMT"
                },
                "meta_tags": {
                    "description": "技术相关元标签（已排除网站信息中的标准标签）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "generator": "WordPress"
                    }
                },
                "os": {
                    "description": "操作系统",
                    "type": "string",
                    "example": "Linux"
                },
                "powered_by": {
                    "description": "X-Powered-By",
                    "type": "string",
                    "example": "PHP/8.1.0"
                },
                "security_headers": {
                    "description": "安全响应头",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "Strict-Transport-Security": "max-age=31536000"
                    }
                },
                "server": {
                    "description": "服务器信息（从ServerInfo整合）",
                    "type": "string",
                    "example": "nginx/1.20.1"
                },
                "technologies": {
                    "description": "技术栈检测（从httpx和HTML分析）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Nginx",
                        "PHP"
                    ]
                }
            }
        },
        "models.WebsiteInfo": {
            "description": "网站基础元信息",
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Example Author"
                },
                "charset": {
                    "type": "string",
                    "example": "UTF-8"
                },
                "description": {
                    "type": "string",
                    "example": "This is an example domain"
                },
                "generator": {
                    "type": "string",
                    "example": "WordPress"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "example",
                        "domain"
                    ]
                },
                "language": {
                    "type": "string",
                    "example": "en"
                },
                "robots": {
                    "type": "string",
                    "example": "index, follow"
                },
                "title": {
                    "type": "string",
                    "example": "Example Domain"
                },
                "viewport": {
                    "type": "string",
                    "example": "width=device-width, initial-scale=1"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "可选：Bearer token认证（当前版本暂未启用）",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
Title:            "WebCheckly API",
		Description:      "WebCheckly 网站检测服务 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
